/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hogar
 */
public class RentaCarro extends javax.swing.JFrame {

    /**
     * Creates new form RentaCarro
     */
    public RentaCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(Agregar)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(Agregar)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
//        String PlacaS;
//        String MarcaS;
//        String ModeloS;
//        String AnoS;
//        String IdSede;
//        try{
//        if(!"".equals(Placa.getText())){
//            throw new Exception("Placa no ingresada");
//        }
//        PlacaS = "\"" + Placa.getText() + "\"";
//        if(!Marca.getSelectedItem().equals("--Seleccione--")){
//            if(Marca.getSelectedItem().equals("Otro")){
//                if(!Otro.getText().equals("")){
//                    MarcaS = "\"" + Otro.getText() + "\"";
//                }else{
//                    throw new Exception("Marca no ingresada");
//                }
//            }else{
//                MarcaS = "\"" + Otro.getText() + "\"";
//            }
//        }else{
//            throw new Exception();
//        }
//        try{
//            if(!Modelo.getSelectedItem().equals("--Seleccione--")){
//                if(Modelo.getSelectedItem().equals("Otro")){
//                    if(!OtroM.getText().equals("")){
//                        ModeloS = "\"" + OtroM.getText()+ "\"";
//                    }else{
//                        throw new Exception();
//                    }
//                }else{
//                    ModeloS ="\""+  OtroM.getText()+ "\"";
//                }
//            }else{
//                throw new Exception();
//            }
//        }catch(java.lang.NullPointerException npe){
//            throw new Exception();
//        }
//        if(!Desde.getText().equals(Hasta.getText().equals(""))){
//            throw new Exception();
//        }
//        AnoS = Desde.getText().toString();
//        if(!Ubicacion.getSelectedItem().equals("--Seleccione--")){
//            IdSede = Ubicacion.getSelectedItem().toString();
//        }else{
//            throw new Exception();
//        }
//        String query = "Insert Into Auto (Placa, Marca, Modelo, Año, IdSede) Values (" + PlacaS + ", " + MarcaS + ", " + ModeloS + ", " + AnoS + ", " + IdSede;
//        try{
//            Statement cmd = Conexion.link.createStatement();
//            ResultSet rs = cmd.executeQuery(query);
//            DefaultTableModel table = Conexion.buildTableModel(rs);
//            JTable tabla = new JTable(table);
//            JOptionPane.showMessageDialog(null, new JScrollPane(tabla));
//        }catch(Exception e){
//            System.out.println(query);
//            System.out.println(e.getMessage());
//        }
//        }catch(Exception e){
//            
//        }
    }//GEN-LAST:event_AgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    // End of variables declaration//GEN-END:variables
}
